### ISSUE TITLE
[Dev] Short term roadmap

### ISSUE THREAD

**Issue by RAlexis** [RAlexis/arcemu_548#1]
- [ ] remove useless messages/comments & cleanup (WorldSocket.cpp, Object.cpp, CharacterHandler.cpp etc)
- [ ] move Player::BuildEnumData to CharacterHandler.cpp
- [ ] new opcode handler, implement STATUS_UNHANDLED to prevent sending (old and unupdated) packets that might crash the server
- [ ] fix SMSG_ADDON_INFO
- [ ] add missing DBCs
